[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NODE_VERSION = "20.11.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_EMAILJS_SERVICE_ID = "${NEXT_PUBLIC_EMAILJS_SERVICE_ID}"
  NEXT_PUBLIC_EMAILJS_TEMPLATE_ID = "${NEXT_PUBLIC_EMAILJS_TEMPLATE_ID}"
  NEXT_PUBLIC_EMAILJS_PUBLIC_KEY = "${NEXT_PUBLIC_EMAILJS_PUBLIC_KEY}" 